# Generated by Django 4.0.2 on 2022-03-08 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import metaMaskAuth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletAuthModel",
            fields=[
                ("public_address", models.TextField(primary_key=True, serialize=False)),
                (
                    "nonce",
                    models.TextField(default=metaMaskAuth.models.generate_random),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
