# Generated by Django 4.1.3 on 2022-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metaMaskAuth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletauthmodel",
            name="nonce_stale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="walletauthmodel",
            name="refreshed_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Refreshed"),
        ),
    ]
